animeClub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('anime_reviews.urls'))
]

anime_reviews/urls.py
from django.urls import path
from . import views, views_users, view_reviews

from django.contrib.auth import views as auth_views

app_name = 'anime_reviews'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('user/profile/<int:user_pk>/', views_users.user_profile, name='user_profile'),
    path('user/profile/', views_users.my_user_profile, name='my_user_profile'),
    path('user/profile/edit/', views_users.edit_profile, name='edit_profile'),
    path('club/meeting/', views_users.meeting_place, name='meeting'),
    path('club/announcements/', views_users.announcements, name='announcements'),
    path('club/announcements/<int:id>/', views_users.announcement_detail, name='announcement_detail'),
    path('club/announcements/edit/<int:id>/', views_users.edit_announcement, name='edit_announcement'),
    path('club/announcements/add/', views_users.add_announcement, name='add_announcement'),

    path('accounts/login/', views_users.login_and_signup, name='login_and_signup'),
    path('accounts/logout/', views_users.user_logout, name='logout'),
    path('register/', views_users.register, name='register'),

    path('anime/search/', view_reviews.search_anime, name='anime_search'),
    path('anime/detail/<int:anime_id>/', view_reviews.anime_detail, name='anime_detail'),
    path('reviews/latest/', view_reviews.latest_reviews, name='latest_reviews'),

    path('reviews/new/<int:anime_id>/', view_reviews.new_review, name='new_review'),
    path('review/edit/<int:review_id>/', view_reviews.edit_review, name='edit_review'),
    path('review/delete/<int:review_id>/', view_reviews.delete_review, name='delete_review'),
    path('review/detail/<int:review_id>/', view_reviews.review_detail, name='review_detail'),

]

anime_reviews/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
# Create your models here.


class Review(models.Model):
    user = models.ForeignKey('auth.User', blank=False, on_delete=models.CASCADE)
    comments = models.TextField(max_length=300)
    posted_date = models.DateTimeField(auto_now_add=True, blank=True)
    modified_date = models.DateTimeField(auto_now=True, blank=True)
    positive_review = models.BooleanField()
    likes = models.IntegerField(blank=True, default=0)
    anime_id = models.IntegerField()
    anime_title = models.CharField(max_length=200)
    episode = models.IntegerField()
    season = models.IntegerField()

    def __str__(self):
        return f'Anime: {self.anime_title} Date posted: {self.posted_date}'

    def add_like(self):
        self.likes += 1
        self.save()

    def add_dislike(self):
        self.likes -= 1
        self.save()


class UserProfile(models.Model):
    user = models.ForeignKey('auth.User', blank=False, null=True, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='user_images/', blank=True, null=True)
    bio = models.TextField(null=True, blank=True)


class Announcement(models.Model):
    subject = models.CharField(max_length=200)
    details = models.TextField()
    posted_date = models.DateTimeField(auto_now_add=True, blank=True)
    modified_date = models.DateTimeField(auto_now=True, blank=True)
    link = models.CharField(max_length=200)

    def __str__(self):
        return f'Anime: {self.subject} Date posted: {self.posted_date}'

    def publish(self):
        self.modified_date = datetime.now()
        self.save()

anime_reviews/forms.py
from django import forms
from .models import Review, UserProfile, Announcement

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ValidationError


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)


    def clean_username(self):

        username = self.cleaned_data['username']

        if not username:
            raise ValidationError('Please enter a username')

        if User.objects.filter(username__iexact=username).exists():
            raise ValidationError('A user with that username already exists')

        return username


    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if not first_name:
            raise ValidationError('Please enter your first name')

        return first_name


    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if not last_name:
            raise ValidationError('Please enter your last name')

        return last_name


    def clean_email(self):
        email = self.cleaned_data['email']
        if not email:
            raise ValidationError('Please enter an email address')

        if User.objects.filter(email__iexact=email).exists():
            raise ValidationError('A user with that email address already exists')

        return email


    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save(commit=False)
        user.username = self.cleaned_data['username']
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user


class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput)
    password = forms.CharField(widget=forms.PasswordInput)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('bio', 'photo')


class AnimeSearchForm(forms.Form):
    anime_search = forms.CharField(label='Anime Name', max_length=200)


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('season', 'episode', 'comments', 'positive_review')


class NewAnnouncementForm(forms.ModelForm):
    class Meta:
        model = Announcement
        fields = ('subject', 'details', 'link')

anime_reviews/views.py
from django.shortcuts import render

# Create your views here.

def homepage(request):
    return render(request, 'anime_reviews/home.html')

anime_reviews/templates/anime_reviews/announcements/add_announcement.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="well well-lg">
        <h1>Edit Announcement</h1>
        <form action="{% url 'anime_reviews:add_announcement' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-default">Add</button>
        </form>
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/announcements/announcement_detail.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    <div class="well well-lg">
    {% if request.user.is_staff %}
        <a href="{% url 'anime_reviews:edit_announcement' id=a.pk %}" class="glyphicon glyphicon-pencil"></a>
    {% endif %}
        <h1>{{ a.subject }}</h1>
        <p id="announcement_date">{{ a.posted_date }}</p>
        <h2>Details:</h2>
        <p>{{ a.details }}</p>
        {% if a.link %}
            Link: <a href="{{ a.link }}">{{ a.link }}</a>
        {% endif %}
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/announcements/club_page.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    <div class="well">
    <h1>Club Announcements</h1>
        {% if request.user.is_staff %}
            <a href="{% url 'anime_reviews:add_announcement' %}" class="glyphicon glyphicon-plus"></a>
        {% endif %}
    </div>
    <div class="well well-lg">
    {% for a in announcements %}
        <P>{{ a.posted_date }}</P>
        <h2><a href="{% url 'anime_reviews:announcement_detail' id=a.id %}">{{ a.subject }}</a></h2>
        <p>{{ a.details|truncatewords:30 }}</p>
        <hr>
    {% empty %}
        <P>No announcements</P>
    {% endfor %}
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/announcements/edit_announcement.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="well well-lg">
        <h1>Edit Announcement</h1>
        <form action="{% url 'anime_reviews:edit_announcement' id=a.pk%}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-default">Edit</button>
        </form>
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Minneapolis Otaku Club Web App</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>


    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<div class="container">
    <div class="jumbotron">
        <h1><a href="{% url 'anime_reviews:homepage' %}" class="nonunderline">Otaku Club</a></h1>
        {% if request.user.is_authenticated %}
            <span id='welcome_user_msg'>You are logged in, <a class="glyphicon glyphicon-user" href="{% url 'anime_reviews:user_profile' user_pk=request.user.pk %}"></a>.  <a class="glyphicon glyphicon-log-out" href="{% url 'anime_reviews:logout' %}"></a></span>
        {% else %}
            <span id='login_or_sign_up'><a class="glyphicon glyphicon-log-in" href="{% url 'anime_reviews:login_and_signup' %}?next={{ request.path }}"></a></span>
        {% endif %}
        <span id="anime_search"><a href="{% url 'anime_reviews:anime_search' %}" class="nonunderline">Search</a></span>
        <span id="meeting_place"><a href="{% url 'anime_reviews:meeting' %}" class="nonunderline">Meeting</a></span>
        <span id="announcements"><a href="{% url 'anime_reviews:announcements' %}" class="nonunderline">Announcements</a></span>
        <span id="anime_search"><a href="{% url 'anime_reviews:latest_reviews' %}" class="nonunderline">Reviews</a></span>
    </div>
</div>
<body>
{% if message %}
    <div class="alert alert-warning">
        <p>
          {{ message }}
        </p>
    </div>
{% endif %}

<div class="container">
    {% block content %}
    {% endblock %}
    <div class="well">
       <P>A web app written in Django by an average otaku</P>
    </div>
</div>
</body>

</html>

anime_reviews/templates/anime_reviews/directions/meeting.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
        <div class="well well-lg">
            <h3>
                Here is where we meetup: The caribou on the corner of 81st and Central Avenue on Sundays.
                Around 3 o' clock pm
            </h3>
            <div id="map" style="width: 1000px; height: 1000px;">

            </div>
        </div>
    <script>
    function initMap() {
        // The location of Uluru
        var meeting = {lat: 45.114920, lng: -93.241063};
        // The map, centered at Uluru
        var map = new google.maps.Map(
        document.getElementById('map'), {zoom: 18, center: meeting});
        // The marker, positioned at Uluru
        var marker = new google.maps.Marker({position: meeting, map: map});
    }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key={{ key }}&callback=initMap">
    </script>
{% endblock %}

anime_reviews/templates/anime_reviews/home.html
{% extends 'anime_reviews/base.html'%}
{% block content %}
    <div class="well well-lg">
        <P>Welcome to the Minneapolis Otaku Club Web App</p>
        <P>Welcome to the club, here you could review anime episodes you watched, create threads related to anime</P>
        <P>Keep the discord civil.</P>
        <P>Use the links above to navigate</p>
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/reviews/anime_detail.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    <div class="container">
        <a href="{% url 'anime_reviews:new_review' anime_id=show.mal_id%}"><button class="btn btn-primary" id="add_review_button">Add review</button></a>
        <div class="well well-lg">
            <h2>{{ show.title }}</h2>
            <P>{{ show.title_english }}</P>

            <img class="img-rounded" id="anime_image" src={{ show.image_url }}>

            <p>Number of episodes: {{ show.episodes }}</p>
            <p>Status: {{ show.status }}</p>
            <p>Score users gave it: {{ show.score }}</p>
            <p>Plot: {{ show.synopsis }}</p>
        </div>
        {% for review in reviews %}
            <div class="well well-md">
                <h2>{{ review.anime_title }}</h2>
                <p>Episode: {{ review.episode }}</p>
                <p>Comments: {{ review.comments|truncatewords:30 }}</p>
            </div>
        {% empty %}
            <div class="well">
                <p>No reviews for this anime</p>
            </div>
        {% endfor %}
    </div>

{% endblock %}

anime_reviews/templates/anime_reviews/reviews/anime_search.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="well">
    <form id="anime_search_form" action="{% url 'anime_reviews:anime_search' %}" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Search</button>
    </form>
        {% for show in shows %}
            <a href="{% url 'anime_reviews:anime_detail' anime_id=show.mal_id %}">{{ show.title }}</a>
            <p> Synopsis: {{ show.synopsis|truncatewords:30 }}</p>
            <hr>
        {% empty %}
            <div>Search for an anime tv show</div>
        {% endfor %}
    </div>

{% endblock %}

anime_reviews/templates/anime_reviews/reviews/edit_review.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="well well-lg">
        <h1>Review about {{ show.anime_title }}</h1>
        <h2>Any changes you have had with this review</h2>
        <form id="new_review_form" action="{% url 'anime_reviews:edit_review' review_id=show.id %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>

{% endblock %}

anime_reviews/templates/anime_reviews/reviews/new_review.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="well well-md">
        <h1>Review about {{ show.title }}</h1>
        <h2>Tell us what you think of this episode or anime!</h2>
        <form id="new_review_form" action="{% url 'anime_reviews:new_review' anime_id=show.mal_id%}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Add</button>
        </form>
    </div>
{% endblock %}

anime_reviews/templates/anime_reviews/reviews/review_detail.html
{% extends 'anime_reviews/base.html' %}
{% block content %}

        <div class="well">
            <h1>Review by {{ review.user.username }}</h1>
            <h2>{{ review.anime_title }}</h2>

            <h2>Season {{ review.season }} episode {{ review.episode }}</h2>
            <p>Comments: {{ review.comments }}</p>
            {% if review.user == request.user %}
                <a class="btn btn-warning" role="button" href="{% url 'anime_reviews:edit_review' review_id=review.id %}">Edit Review</a>
                <a class="btn btn-danger" role="button" href="{% url 'anime_reviews:delete_review' review_id=review.id %}">Delete Review</a>
            {% endif %}
        </div>


{% endblock %}

anime_reviews/templates/anime_reviews/reviews/reviews.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    <div class="well">
        <P>Latest Reviews</P>
        <hr>
        {% for r in reviews %}
            <P>Posted date: {{ r.posted_date }}</P>
            <h2><a href="{% url 'anime_reviews:anime_detail' anime_id=r.anime_id %}">{{ r.anime_title }}</a></h2>
            <p>Season: {{ r.season }} Episode: {{ r.episode }}</p>
            <p>Comments: {{ r.comments|truncatewords:30 }}</p>
        {% empty %}
            <h2>No notes.</h2>
        {% endfor %}
    </div>

{% endblock %}

anime_reviews/templates/users/edit_profile.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
    {% load crispy_forms_tags %}
    <P>Edit Profile</P>
    <form id="edit_profile_form" method="POST" action="{% url 'anime_reviews:edit_profile' %}">{% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-default" type="submit">Edit</button>
    </form>
{% endblock %}

anime_reviews/templates/users/user_profile.html
{% extends 'anime_reviews/base.html' %}
{% block content %}
<div class="well well-lg">
{% if request.user.is_authenticated and request.user == profile.user%}
    <h1>Welcome to your profile page</h1>
    <a href="{% url 'anime_reviews:edit_profile' %}"><span class="glyphicon glyphicon-pencil" id="edit_profile"></span></a>
{% else %}
    <h1>Welcome to {{ user.username }}'s profile</h1>
{% endif %}

    <p>Member since: {{ user.date_joined }}</p>
    {% if profile %}
        {% if profile.photo %}
            <p>Member photo: <span id="member_photo">{{ profile.photo }}</span></p>
        {% else %}
            <p>No member photo</p>
        {% endif %}
        <p>Bio: {{ profile.bio }}</p>
    {% else %}
        <p>Update your profile so other club members can see what you are about</p>
    {% endif %}
</div>


<div class="well well-lg">
    <P>Latest reviews: </P>

    {% for r in reviews %}

            <h2><a href="{% url 'anime_reviews:anime_detail' anime_id=r.anime_id %}">{{ r.anime_title }}</a></h2>
            <p>Episode: {{ r.episode }}</p>
            <p>Comments: {{ r.comments|truncatewords:30 }}</p>
        <p><a href="{% url 'anime_reviews:review_detail' review_id=r.id %}">Details</a></p>

    {% empty %}
        <p>You have no reviews yet!</p>
    {% endfor %}

</div>


{% endblock %}